In [3]:
#Numpy has multidimensional array ndarray containing
    #-> the actual data
    #-> some matadata describing the data
import numpy as np

In [4]:
a= np.arange(5)
a.dtype

dtype('int64')

In [5]:
a

array([0, 1, 2, 3, 4])

In [10]:
#printing the shape of the vector
a.shape

(5,)

In [17]:
#creating  multidimensional array

m= np.array([np.arange(5),np.arange(5)])
print m
print m.shape


[[0 1 2 3 4]
 [0 1 2 3 4]]
(2, 5)


In [23]:
#comples datatype
i = 1.0
comp = complex(i)
print comp
print "imaginory part", comp.imag
print "real part", comp.real

(1+0j)
imaginory part 0.0
real part 1.0


In [24]:
# the size in bytes is given by the itemsize attribute
a.dtype.itemsize

8

In [49]:
# we can use a record datatype to store the hetrogeneous data

r = np.dtype([('name', str,40), ('numitems',int), ('price', float)])
print r


[('name', 'S40'), ('numitems', '<i8'), ('price', '<f8')]


In [56]:
# adding the data to record
itemz= np.array([('DVD', 2 ,42), ('butter', 5, 10)], dtype=r)
print itemz

#appending records to already existing array
print " adding new record"

itemz= np.append(itemz,np.array([('pen', 5, 10)], dtype=itemz.dtype))

print itemz
                    

[('DVD', 2,  42.) ('butter', 5,  10.)]
 adding new record
[('DVD', 2,  42.) ('butter', 5,  10.) ('pen', 5,  10.)]


In [57]:
# slicing the nparry

#slicing is similar to the slicing of the list

s= np.arange(9)
print s[3:7] #slice 3-6

print s[2:8:2] #slice 2-8 with a step size of 2

print s[::-1] # reverse the array

[3 4 5 6]
[2 4 6]
[8 7 6 5 4 3 2 1 0]
