In [3]:
#Numpy has multidimensional array ndarray containing
    #-> the actual data
    #-> some matadata describing the data
import numpy as np

In [4]:
a= np.arange(5)
a.dtype

dtype('int64')

In [5]:
a

array([0, 1, 2, 3, 4])

In [10]:
#printing the shape of the vector
a.shape

(5,)

In [17]:
#creating  multidimensional array

m= np.array([np.arange(5),np.arange(5)])
print m
print m.shape


[[0 1 2 3 4]
 [0 1 2 3 4]]
(2, 5)


In [23]:
#comples datatype
i = 1.0
comp = complex(i)
print comp
print "imaginory part", comp.imag
print "real part", comp.real

(1+0j)
imaginory part 0.0
real part 1.0


In [24]:
# the size in bytes is given by the itemsize attribute
a.dtype.itemsize

8

In [30]:
# we can use a record datatype to store the hetrogeneous data

r = np.dtype([('name', str,40), ('numitems',int), ('price', float)])
print r


[('name', 'S40'), ('numitems', '<i8'), ('price', '<f8')]


In [39]:
# adding the data to record
itemz= np.array([('DVD', 2 ,42), ('butter', 5, 10)])
itemz[2]= np.array([('pen', 5, 10)])

itemz

IndexError: index 2 is out of bounds for axis 0 with size 2